# <center>NumPy Arrays and Indexing

In [1]:
import numpy as np

### 1. Create a numpy array called ‘height_in_inches’ from a list of 10 numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71].

In [2]:
height_in_inches = [66, 68, 71, 64, 61, 74, 64, 65, 70, 71]

### 2. Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.

In [3]:
height_in_feet = list(map(lambda h: h/12, height_in_inches))

In [4]:
print('Height_in_feet has the following list values:', '  '.join(map(str, height_in_feet)))

Height_in_feet has the following list values: 5.5  5.666666666666667  5.916666666666667  5.333333333333333  5.083333333333333  6.166666666666667  5.333333333333333  5.416666666666667  5.833333333333333  5.916666666666667


### 3. Create a 5x5 array of zeros. 

In [5]:
np_zeros = np.zeros((5,5), dtype=int)  # np.zeros((5,5)) would create same array's size but of type float

In [6]:
print(np_zeros)

print('\nnp_zeros is of type:', np_zeros.dtype)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

np_zeros is of type: int32


### 4. Create an array of random floating point numbers between 0 and 100. 

In [7]:
random_np = np.linspace(0,100)
print(random_np)

[  0.           2.04081633   4.08163265   6.12244898   8.16326531
  10.20408163  12.24489796  14.28571429  16.32653061  18.36734694
  20.40816327  22.44897959  24.48979592  26.53061224  28.57142857
  30.6122449   32.65306122  34.69387755  36.73469388  38.7755102
  40.81632653  42.85714286  44.89795918  46.93877551  48.97959184
  51.02040816  53.06122449  55.10204082  57.14285714  59.18367347
  61.2244898   63.26530612  65.30612245  67.34693878  69.3877551
  71.42857143  73.46938776  75.51020408  77.55102041  79.59183673
  81.63265306  83.67346939  85.71428571  87.75510204  89.79591837
  91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


### 5. Create an array of numbers from 0 to 75 in increments of 5

In [8]:
rando_np = np.arange(0,75,5)
print(rando_np)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70]


In [9]:
random2_np = np.linspace(0,75,5)  #Note: 5 indicates the number of steps, hence the 5 values
print(random2_np)

[ 0.   18.75 37.5  56.25 75.  ]
